-- Pilar 5 (parte 3): logging centralizado

create table public.system_logs (
  id bigint generated by default as identity primary key,
  level text not null,
  event text not null,
  details jsonb,
  created_at timestamptz not null default now()
);

alter table public.system_logs enable row level security;
-- Sem policies: só o service role acessa.
